/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as DecouvrirRouteImport } from './routes/decouvrir'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TitreSlugRouteImport } from './routes/titre.$slug'

const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const DecouvrirRoute = DecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TitreSlugRoute = TitreSlugRouteImport.update({
  id: '/titre/$slug',
  path: '/titre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decouvrir': typeof DecouvrirRoute
  '/recherche': typeof RechercheRoute
  '/titre/$slug': typeof TitreSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decouvrir': typeof DecouvrirRoute
  '/recherche': typeof RechercheRoute
  '/titre/$slug': typeof TitreSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decouvrir': typeof DecouvrirRoute
  '/recherche': typeof RechercheRoute
  '/titre/$slug': typeof TitreSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decouvrir' | '/recherche' | '/titre/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decouvrir' | '/recherche' | '/titre/$slug'
  id: '__root__' | '/' | '/decouvrir' | '/recherche' | '/titre/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecouvrirRoute: typeof DecouvrirRoute
  RechercheRoute: typeof RechercheRoute
  TitreSlugRoute: typeof TitreSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decouvrir': {
      id: '/decouvrir'
      path: '/decouvrir'
      fullPath: '/decouvrir'
      preLoaderRoute: typeof DecouvrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titre/$slug': {
      id: '/titre/$slug'
      path: '/titre/$slug'
      fullPath: '/titre/$slug'
      preLoaderRoute: typeof TitreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecouvrirRoute: DecouvrirRoute,
  RechercheRoute: RechercheRoute,
  TitreSlugRoute: TitreSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
